// +build amd64

// Code generated by cmd/cgo -godefs; DO NOT EDIT.
// cgo -godefs types_net.go

package c

const (
	IPPROTO_TCP = 0x6
)

const (
	TCP_ESTABLISHED	= 0x1
	TCP_SYN_SENT	= 0x2
	TCP_SYN_RECV	= 0x3
	TCP_FIN_WAIT1	= 0x4
	TCP_FIN_WAIT2	= 0x5
	TCP_TIME_WAIT	= 0x6
	TCP_CLOSE	= 0x7
	TCP_CLOSE_WAIT	= 0x8
	TCP_LAST_ACK	= 0x9
	TCP_LISTEN	= 0xa
	TCP_CLOSING	= 0xb
)
