/*
 * Author: fasion
 * Created time: 2023-12-27 16:47:06
 * Last Modified by: fasion
 * Last Modified time: 2023-12-27 16:47:06
 */
// +build amd64

// Code generated by cmd/cgo -godefs; DO NOT EDIT.
// cgo -godefs types_elfauxv.go

package c

const (
	AT_NULL			= 0x0
	AT_IGNORE		= 0x1
	AT_EXECFD		= 0x2
	AT_PHDR			= 0x3
	AT_PHENT		= 0x4
	AT_PHNUM		= 0x5
	AT_PAGESZ		= 0x6
	AT_BASE			= 0x7
	AT_FLAGS		= 0x8
	AT_ENTRY		= 0x9
	AT_NOTELF		= 0xa
	AT_UID			= 0xb
	AT_EUID			= 0xc
	AT_GID			= 0xd
	AT_EGID			= 0xe
	AT_PLATFORM		= 0xf
	AT_HWCAP		= 0x10
	AT_CLKTCK		= 0x11
	AT_SECURE		= 0x17
	AT_BASE_PLATFORM	= 0x18
	AT_RANDOM		= 0x19
	AT_HWCAP2		= 0x1a
	AT_EXECFN		= 0x1f
)
