// +build amd64

// Code generated by cmd/cgo -godefs; DO NOT EDIT.
// cgo -godefs types_scsi.go

package c

const (
	TYPE_DISK		= 0x0
	TYPE_TAPE		= 0x1
	TYPE_PROCESSOR		= 0x3
	TYPE_WORM		= 0x4
	TYPE_ROM		= 0x5
	TYPE_SCANNER		= 0x6
	TYPE_MOD		= 0x7
	TYPE_MEDIUM_CHANGER	= 0x8

	TYPE_NO_LUN	= 0x7f
)
