/*
 * Author: fasion
 * Created time: 2023-12-27 16:46:47
 * Last Modified by: fasion
 * Last Modified time: 2023-12-27 16:46:47
 */
// +build amd64

// Code generated by cmd/cgo -godefs; DO NOT EDIT.
// cgo -godefs types_common.go

package c

type UnsignedLong_c = uint64
