// +build amd64

// Code generated by cmd/cgo -godefs; DO NOT EDIT.
// cgo -godefs types_sock_diag.go

package netlink

const (
	SOCK_DIAG_BY_FAMILY	= 0x14

	INET_DIAG_MEMINFO	= 0x1
	INET_DIAG_INFO		= 0x2
	INET_DIAG_CONG		= 0x4
	INET_DIAG_TOS		= 0x5
	INET_DIAG_TCLASS	= 0x6
	INET_DIAG_SKMEMINFO	= 0x7

	IPPROTO_TCP	= 0x6

	TCPDIAG_GETSOCK	= 0x12
)

type InetDiagReq_c struct {
	Family	uint8
	Src_len	uint8
	Dst_len	uint8
	Ext	uint8
	Id	InetDiagSockId_c
	States	uint32
	Dbs	uint32
}
type InetDiagMsg_c struct {
	Family	uint8
	State	uint8
	Timer	uint8
	Retrans	uint8
	Id	InetDiagSockId_c
	Expires	uint32
	Rqueue	uint32
	Wqueue	uint32
	Uid	uint32
	Inode	uint32
}
type InetDiagSockId_c struct {
	Sport	uint16
	Dport	uint16
	Src	[4]uint32
	Dst	[4]uint32
	If	uint32
	Cookie	[2]uint32
}
type InetDiagReqV2_c struct {
	Sdiag_family	uint8
	Sdiag_protocol	uint8
	Idiag_ext	uint8
	Pad		uint8
	Idiag_states	uint32
	Id		InetDiagSockId_c
}

const (
	SizeOfInetDiagReq_c	= 0x3c
	SizeOfInetDiagMsg	= 0x48
	SizeOfInetDiagReqV2_c	= 0x38
)
