// +build amd64

// Code generated by cmd/cgo -godefs; DO NOT EDIT.
// cgo -godefs types_netlink.go

package netlink

const (
	AF_NETLINK	= 0x10
	SOCK_DGRAM	= 0x2
	SOCK_RAW	= 0x3

	NETLINK_ROUTE	= 0x0

	NETLINK_USERSOCK	= 0x2
	NETLINK_FIREWALL	= 0x3
	NETLINK_INET_DIAG	= 0x4
	NETLINK_SOCK_DIAG	= 0x4
	NETLINK_NFLOG		= 0x5

	NLMSG_NOOP	= 0x1
	NLMSG_ERROR	= 0x2
	NLMSG_DONE	= 0x3

	NLM_F_REQUEST	= 0x1
	NLM_F_MULTI	= 0x2
	NLM_F_ACK	= 0x4
	NLM_F_ECHO	= 0x8

	NLM_F_ROOT	= 0x100
	NLM_F_MATCH	= 0x200
	NLM_F_ATOMIC	= 0x400
	NLM_F_DUMP	= 0x300
)

type NlMsgHdr_c struct {
	Len	uint32
	Type	uint16
	Flags	uint16
	Seq	uint32
	Pid	uint32
}
type NlMsgErr_c struct {
	Error	int32
	Msg	NlMsgHdr_c
}
type SockAddrNl_c struct {
	Family	uint16
	Pad	uint16
	Pid	uint32
	Groups	uint32
}

const (
	SizeofNlMsgHdr_c	= 0x10
	SizeofNlMsgErr_c	= 0x14
	SizeofSockaddrNl_c	= 0xc
)
